
apiVersion: v1
kind: Service
metadata:
  name:  touristmgt-service
spec:
  type: NodePort
  selector:
    app: touristmgt-api
  ports:
    - protocol: TCP
      port: 8083        # The port that this service will expose
      targetPort: 8082 # The containerPort on the pods(container runs)
      nodePort: 30007 #  port on each node's IP